on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'


env:
  pa5: ${{ secrets.pa5 }}


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li5ht4ay-3es/ac5io4s@cron
        with:
          token: ${{ env.pa5 }}
