on:
  workflow_dispatch:
  # push:


env:
  pa5: ${{ secrets.pa5 }}


jobs:

  mingw-win-xp:
    runs-on: windows-latest

    steps:
      - uses: li5ht4ay-3es/ac5io4s@user-action


      - uses: li5ht4ay-3es/ac5io4s@checkout-branch
        with:
          token: ${{ env.pa5 }}


      - uses: li5ht4ay-3es/ac5io4s@mingw-install
        with:
          arch: x86
          os: winxp


      - run: |
          & $env:MINGW_CC --version



  mingw-win-32:
    runs-on: windows-latest

    steps:
      - uses: li5ht4ay-3es/ac5io4s@user-action


      - uses: li5ht4ay-3es/ac5io4s@checkout-branch
        with:
          token: ${{ env.pa5 }}


      - uses: li5ht4ay-3es/ac5io4s@mingw-install
        with:
          arch: x86


      - run: |
          & $env:MINGW_CC --version



  mingw-win-64:
    runs-on: windows-latest

    steps:
      - uses: li5ht4ay-3es/ac5io4s@user-action


      - uses: li5ht4ay-3es/ac5io4s@checkout-branch
        with:
          token: ${{ env.pa5 }}


      - uses: li5ht4ay-3es/ac5io4s@mingw-install


      - run: |
          & $env:MINGW_CC --version



  mingw-ubuntu-32:
    runs-on: ubuntu-latest

    steps:
      - uses: li5ht4ay-3es/ac5io4s@user-action


      - uses: li5ht4ay-3es/ac5io4s@checkout-branch
        with:
          token: ${{ env.pa5 }}


      - uses: li5ht4ay-3es/ac5io4s@mingw-install
        with:
          arch: x86


      - run: |
          $MINGW_CC --version



  mingw-ubuntu-64:
    runs-on: ubuntu-latest

    steps:
      - uses: li5ht4ay-3es/ac5io4s@user-action


      - uses: li5ht4ay-3es/ac5io4s@checkout-branch
        with:
          token: ${{ env.pa5 }}


      - uses: li5ht4ay-3es/ac5io4s@mingw-install


      - run: |
          $MINGW_CC --version
