on:
  workflow_dispatch:
  # push:


env:
  pa5: ${{ secrets.pa5 }}


jobs:

  squash-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: li5ht4ay-3es/ac5io4s@user-action


      - uses: li5ht4ay-3es/ac5io4s@checkout-repo
        with:
          token: "${{ env.pa5 }}"


      - uses: li5ht4ay-3es/ac5io4s@erase-commit
        # with:
        #   depth: 1


      - uses: li5ht4ay-3es/ac5io4s@squash-repo
        # with:
        #   depth: 500
