on:
  workflow_dispatch:
  # push:


env:
  pa5: ${{ secrets.pa5 }}


jobs:

  checkout-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: li5ht4ay-ye4/ac5io4s@user-action


      - uses: li5ht4ay-ye4/ac5io4s@checkout-repo
        with:
          token: "${{ env.pa5 }}"
