on:
  workflow_dispatch:
  # push:


env:
  pa5: ${{ secrets.pa5 }}


jobs:

  rebase-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: li5ht4ay-3es/ac5io4s@user-action


      - uses: li5ht4ay-3es/ac5io4s@checkout-repo
        with:
          token: "${{ env.pa5 }}"


      - uses: li5ht4ay-3es/ac5io4s@rebase-repo
        with:
          remote_repo: li5ht4ay-3es/ac5io4s
          remote_branch: main
